project:
  type: website
  output-dir: docs
website:
  favicon: images/blog-logo.ico
  title: "Where the branches meet the roots"
  site-url: https://ajstamm.github.io/musings/
  image: images/water-tree-root-mosaic.png
  navbar:
    right:
      - text: Musings blog
        href: blog.qmd
      - icon: github
        text: Website GitHub
        href: https://github.com/ajstamm/musings
      - icon: rss
        text: RSS feed
        href: blog.xml
      - text: Archive
        href: archive.qmd
format:
  html:
    respect-user-color-scheme: true
    theme: 
      dark: darkly
      light: cosmo
    css: styles.css
title-block-banner: images/water-tree-root-mosaic.png



