project:
  type: website
  output-dir: _site
website:
  title: "Stamm Musings"
  navbar:
    right:
      - about.qmd
      - icon: github
        text: GitHub
        href: https://github.com/ajstamm
format:
  html:
    theme: cosmo
    css: styles.css



